/**
 * Type Definitions for Development Environment Cloner
 * Generated by AGI Code Generator
 */

export interface EnvironmentSnapshot {
    metadata: EnvironmentMetadata;
    vscode: VSCodeSettings;
    extensions: ExtensionCollection;
    repositories: RepositoryCollection;
    dependencies: DependencyCollection;
    aiInsights: AIInsights;
}

export interface EnvironmentMetadata {
    id: string;
    name: string;
    version: string;
    created: Date;
    author: UserInfo;
    tags: string[];
    platform: PlatformInfo;
}

export interface UserInfo {
    name: string;
    email: string;
}

export interface PlatformInfo {
    os: string;
    arch: string;
    nodeVersion: string;
}

export interface VSCodeSettings {
    version: string;
    settings: { [key: string]: any };
    keybindings: KeyBinding[];
    snippets: Snippet[];
    tasks: TaskConfiguration[];
    launch: LaunchConfiguration[];
}

export interface KeyBinding {
    key: string;
    command: string;
    when?: string;
}

export interface Snippet {
    name: string;
    prefix: string;
    body: string[];
    description?: string;
}

export interface TaskConfiguration {
    label: string;
    type: string;
    command: string;
    group?: string;
    args?: string[];
}

export interface LaunchConfiguration {
    name: string;
    type: string;
    request: string;
    program?: string;
    [key: string]: any;
}

export interface ExtensionCollection {
    installed: ExtensionInfo[];
    disabled: string[];
    recommendations: string[];
}

export interface ExtensionInfo {
    id: string;
    version: string;
    name: string;
    publisher: string;
    enabled: boolean;
    settings: { [key: string]: any };
}

export interface RepositoryCollection {
    workspace: WorkspaceFolder[];
    git: GitRepository[];
}

export interface WorkspaceFolder {
    name: string;
    uri: string;
}

export interface GitRepository {
    name: string;
    path: string;
    remote: string | null;
    branch: string | null;
}

export interface DependencyCollection {
    system: SystemDependency[];
    runtime: RuntimeDependency[];
    tools: ToolDependency[];
}

export interface SystemDependency {
    name: string;
    version: string;
    type: 'global' | 'local';
}

export interface RuntimeDependency {
    name: string;
    version: string;
    manager: 'npm' | 'pip' | 'cargo' | 'other';
}

export interface ToolDependency {
    name: string;
    version: string;
    path: string;
}

export interface AIInsights {
    optimizations: Optimization[];
    warnings: Warning[];
    compatibility: CompatibilityInfo;
}

export interface Optimization {
    type: 'performance' | 'security' | 'compatibility' | 'productivity';
    title: string;
    description: string;
    impact: 'low' | 'medium' | 'high';
    implementation: string;
}

export interface Warning {
    type: 'security' | 'compatibility' | 'deprecated';
    message: string;
    severity: 'low' | 'medium' | 'high';
}

export interface CompatibilityInfo {
    score: number;
    issues: string[];
}

export interface Conflict {
    type: 'setting' | 'extension' | 'file';
    path: string;
    description: string;
    severity: 'low' | 'medium' | 'high';
    currentValue: any;
    incomingValue: any;
}

export interface Resolution {
    strategy: 'merge' | 'overwrite' | 'skip' | 'custom';
    actions: ResolutionAction[];
    explanation: string;
}

export interface ResolutionAction {
    type: 'setting' | 'extension' | 'file';
    action: 'update' | 'install' | 'remove';
    target: string;
    value: any;
}

export interface CloneResult {
    success: boolean;
    extensionsInstalled: number;
    settingsApplied: number;
    repositoriesCloned: number;
    errors: string[];
    warnings: string[];
}