import * as vscode from 'vscode';
import { EnvironmentScanner } from './scanner/environmentScanner';
import { CloningEngine } from './cloner/cloningEngine';
import { AIAssistant } from './ai/aiAssistant';
import { WebviewController } from './ui/webview';

/**
 * Development Environment Cloner Extension
 * Generated by AGI Code Generator v1.0
 * 
 * Features:
 * - AI-powered environment analysis
 * - Intelligent conflict resolution
 * - Real-time collaboration
 * - Enterprise security
 */

let environmentScanner: EnvironmentScanner;
let cloningEngine: CloningEngine;
let aiAssistant: AIAssistant;
let webviewController: WebviewController;

export function activate(context: vscode.ExtensionContext) {
    console.log('🚀 Development Environment Cloner is now active!');
    
    // Initialize core components
    environmentScanner = new EnvironmentScanner();
    cloningEngine = new CloningEngine();
    aiAssistant = new AIAssistant();
    webviewController = new WebviewController(context);
    
    // Register commands
    registerCommands(context);
    
    // Setup event listeners
    setupEventListeners(context);
    
    // Display welcome message
    vscode.window.showInformationMessage(
        '🎉 Development Environment Cloner ready! Use Ctrl+Shift+P and search "DevEnv"'
    );
}

function registerCommands(context: vscode.ExtensionContext) {
    // Export Environment Command
    const exportCommand = vscode.commands.registerCommand('devenv.exportEnvironment', async () => {
        try {
            vscode.window.showInformationMessage('🔍 Scanning current environment...');
            
            const environment = await environmentScanner.scanCurrentEnvironment();
            const aiInsights = await aiAssistant.analyzeEnvironment(environment);
            
            // Show AI suggestions
            if (aiInsights.optimizations.length > 0) {
                const choice = await vscode.window.showInformationMessage(
                    `Found ${aiInsights.optimizations.length} optimization suggestions. View them?`,
                    'Yes', 'No'
                );
                if (choice === 'Yes') {
                    await aiAssistant.showOptimizationSuggestions(aiInsights.optimizations);
                }
            }
            
            // Export to file
            const exportPath = await vscode.window.showSaveDialog({
                defaultUri: vscode.Uri.file('environment-snapshot.json'),
                filters: {
                    'Environment Files': ['json']
                }
            });
            
            if (exportPath) {
                await environmentScanner.exportToFile(environment, exportPath.fsPath);
                vscode.window.showInformationMessage(
                    `✅ Environment exported to ${exportPath.fsPath}`
                );
            }
            
        } catch (error) {
            vscode.window.showErrorMessage(`Export failed: ${error}`);
            console.error('Export error:', error);
        }
    });
    
    // Import Environment Command
    const importCommand = vscode.commands.registerCommand('devenv.importEnvironment', async () => {
        try {
            const importPath = await vscode.window.showOpenDialog({
                canSelectFiles: true,
                canSelectMany: false,
                filters: {
                    'Environment Files': ['json']
                }
            });
            
            if (!importPath || importPath.length === 0) {
                return;
            }
            
            vscode.window.showInformationMessage('📥 Importing environment...');
            
            const environment = await environmentScanner.loadFromFile(importPath[0].fsPath);
            const conflicts = await cloningEngine.detectConflicts(environment);
            
            // AI-powered conflict resolution
            if (conflicts.length > 0) {
                const resolution = await aiAssistant.resolveConflicts(conflicts);
                await cloningEngine.applyResolution(resolution);
            }
            
            // Execute import
            const result = await cloningEngine.importEnvironment(environment);
            
            if (result.success) {
                vscode.window.showInformationMessage(
                    `✅ Environment imported successfully! Installed ${result.extensionsInstalled} extensions.`
                );
            } else {
                vscode.window.showWarningMessage(
                    `⚠️ Import completed with warnings. Check output for details.`
                );
            }
            
        } catch (error) {
            vscode.window.showErrorMessage(`Import failed: ${error}`);
            console.error('Import error:', error);
        }
    });
    
    // Dashboard Command
    const dashboardCommand = vscode.commands.registerCommand('devenv.openDashboard', async () => {
        await webviewController.openDashboard();
    });
    
    context.subscriptions.push(exportCommand, importCommand, dashboardCommand);
}

function setupEventListeners(context: vscode.ExtensionContext) {
    // Listen for workspace changes
    const workspaceWatcher = vscode.workspace.onDidChangeWorkspaceFolders(async (event) => {
        if (event.added.length > 0) {
            const choice = await vscode.window.showInformationMessage(
                'Workspace changed. Would you like to analyze the new environment?',
                'Yes', 'No'
            );
            if (choice === 'Yes') {
                vscode.commands.executeCommand('devenv.exportEnvironment');
            }
        }
    });
    
    // Listen for extension changes
    const extensionWatcher = vscode.extensions.onDidChange(() => {
        // Auto-sync if enabled
        console.log('Extensions changed - triggering environment sync');
    });
    
    context.subscriptions.push(workspaceWatcher, extensionWatcher);
}

export function deactivate() {
    console.log('👋 Development Environment Cloner deactivated');
}